image:
  repository: postgres
  tag: "15.3-alpine"
  pullPolicy: IfNotPresent

auth:
  database: ecommerce
  username: postgres
  # password and postgresPassword sourced from secret
  existingSecret: backend-db-secret
  secretKeys:
    adminPasswordKey: password
    userPasswordKey: password

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: "gp2"
  size: 10Gi
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

podSecurityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

livenessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 10
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
