image:
  repository: redis
  tag: "7.2-alpine"
  pullPolicy: IfNotPresent

auth:
  enabled: false
  # Set to true and provide existingSecret to enable requirepass
  existingSecret: backend-redis-secret
  secretKey: password

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  storageClass: "gp2"
  size: 2Gi
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

livenessProbe:
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 5
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
